#---------------------------------#
#      General Configuration      #
#---------------------------------#
version: 0.50.{build}

branches:
  only:
    - master

#---------------------------------#
#    Environment Configuration    #
#---------------------------------#
image: Visual Studio 2017

configuration: Release
platform: x64

#---------------------------------#
#       Build Configuration       #
#---------------------------------#
build:
  parallel: true
  verbosity: normal
